#------SCRIPT TO TRANSFER THE LARGE DATA FILES INTO THE APPROPRIATE DIRECTORIES


export JAS=$WORK/JASMIN_TRANSFER

cd $JAS
cp $JAS/BATH/* $GFILE/BATH/

cp $JAS/DOMAIN/coordinates_ORCA_R12.nc $GFILE/DOMAIN/

cp $GFILE/STARTFILES/OBC/* $OBC
cp $GFILE/STARTFILES/TIDES/* $TIDES
